# Package Development, Testing, and Model Testing

This repository contains materials for the NYU predoctoral economics training program. This
material covers the topics of code modularization, Python package development, unit and
integration testing, and model testing. It was prepared and presented by Chase Coleman
(Valorum Data) and Jim Savage (Schmidt Future).


## 1. Schedule


### Friday, December 6


| Time          | Topic                    | Materials                                                                                                                  |
| :----:        | :---------               | :--------                                                                                                                  |
| 9:00 - 12:30  |                          |                                                                                                                            |
|               | Modularization           |                                                                                                                            |
|               | Project 1                | [Project 1](https://github.com/nyupredocs/modularizationandtesting/blob/master/Projects/Project_1_HendricksLeukhina.ipynb) |
|               | Package Development      | [Day 1 slides](https://github.com/nyupredocs/modularizationandtesting/blob/master/Slides/package_dev_FriAM.pdf)            |
| 12:30 - 13:30 | Lunch                    |                                                                                                                            |
| 13:30 - 17:00 | Wrap up remaining slides |                                                                                                                            |
|               | Project 2                | [Project 2](https://github.com/nyupredocs/modularizationandtesting/blob/master/Projects/Project_2_PackageBuilding.md)      |


### Saturday, December 7

| Time         | Topic               | Materials        |
| :----:       | :---------          | :--------        |


### Sunday, December 8

| Time         | Topic               | Materials        |
| :----:       | :---------          | :--------        |


## 2. Package Development

The following mantra should be more widely adopted: “Don’t write a new package, if there is already a high-quality package that fulfills your needs.”

Below are some examples of scientific projects that the Python community typically deems as “high-quality.”

* [Astropy](https://www.astropy.org/about.html#about-the-astropy-project)
* [Biopython](https://biopython.org/)
* [pyblp](https://pyblp.readthedocs.io/en/stable/)
* [pymc](https://docs.pymc.io/) and Stan](https://mc-stan.org/)
* [sunpy](https://sunpy.org/)
* [quantecon](https://quantecon.org/quantecon-py/)

What do these projects have in common?

Here are some additional readings:

* [Instructions for creating Python package](https://packaging.python.org/tutorials/packaging-projects/)
* [How to develop good R packages](https://www.r-bloggers.com/how-to-develop-good-r-packages-for-open-science/) (for open science): Not about Python but does have some thoughtful points on general package development
* [Open Reproducible Science](https://www.earthdatascience.org/courses/intro-to-earth-data-science/open-reproducible-science/get-started-open-reproducible-science/)
* [Advantages of Modularization in Programming](https://www.techwalla.com/articles/the-advantages-of-modularization-in-programming)
